# Default values for weather-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: timmytiny0/demoapp
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

appId: <APP_ID_INSERT_HERE>
appDefaultCity: London

host: ldn.206.189.245.138.nip.io

isProductionEnv: ""
productionEnvReplicaCount: 2
defaultReplicaCount: 1
