apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: myspace
  labels:
    name: app-pod
    project: northwind
spec:
  containers:
    - name: app
    image: stackupiss/northwind-app:v1
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
    env:
    - name: DB_HOST
      value: localhost