apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deploy
  namespace: myspace
  labels:
    name: db-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-pod
  template:
    # template of the pod i am going to deploy in this
    # deployment (:
    metadata:
      name: db-pod
      namespace: myspace
      labels:
        name: db-pod # matched by service's selector
        project: northwind
    spec:
      containers:
        - name: db
          image: stackupiss/northwind-db:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service

metadata:
  name: db-svc
  namespace: myspace
  labels:
    type: service
    name: db-svc

spec:
  type: ClusterIP
  selector:
    name: db-pod
  ports:
    - port: 3306 # service's port
      targetPort: 3306 # container's port
